name: CD

on:
  # workflow_run:
  #   branches: ["master"]
  #   workflows: ["CI"]
  #   types:
  #     - completed
  workflow_call:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Copy environment file
        run: cp .env.example .env

      # 2. Build and start your containers
      - name: Start containers
        run: docker compose up -d
