name: CD

on:
  # workflow_run:
  #   branches: ["master"]
  #   workflows: ["CI"]
  #   types:
  #     - completed
  workflow_call:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Check out code
        uses: actions/checkout@v7

      - name: Log in to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull Docker Compose images
        run: docker compose pull

      - name: Copy environment file
        run: cp .env.example .env

      # Build and start your containers
      - name: Start containers
        run: docker compose up -d
