name: CI

on:
  push:
    branches: [master]

jobs:
  frontend:
    runs-on: ubuntu-latest

    # This fixes the error by forcing all commands to run inside /frontend
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24' # Specify 18, 20, 22, etc.
          cache: 'npm'       # Caches dependencies to speed up future runs  
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm install --legacy-peer-deps
      
      - name: Run Lint
        run: npm run lint --if-present      

      # 5. Run test suites
      - name: Run Tests
        run: npm test
        
      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          context: ./frontend
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/dev-frontend-img:latest
