name: CI

on:
  push:
    branches: [master]
    #paths-ignore:
     # - '.github/workflows/**'

jobs:
  frontend:
    runs-on: ubuntu-latest

    # This fixes the error by forcing all commands to run inside /frontend
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24' # Specify 18, 20, 22, etc.
          cache: 'npm'       # Caches dependencies to speed up future runs  
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm install --legacy-peer-deps
      
      - name: Run Lint
        run: npm run lint --if-present      

      # 5. Run test suites
      - name: Run Tests
        run: npm test
        
      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          context: ./frontend
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/dev-frontend-img:latest


  backend:
    runs-on: ubuntu-latest

    # This fixes the error by forcing all commands to run inside /frontend
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22' # Specify your preferred Go version (e.g., '1.21', '1.22', '^1.22.0')
          cache: true
          cache-dependency-path-sub-directory: backend

      - name: Install dependencies
        run: go mod download
      
      - name: Run Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          working-directory: backend

      # 3. Run test suites
      - name: Run Tests
        run: go test -v ./...
        
      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          context: ./backend
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/dev-backend-img:latest
