name: Go Dependency Vulnerability Scan

on:
  workflow_call:

jobs:
  govulncheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          # Points the caching mechanism to your backend folder
          cache-dependency-path: backend/go.sum
      
      - name: Download Go dependencies
        working-directory: backend
        run: |
          go mod download
          go mod tidy

      - name: Run govulncheck
        continue-on-error: true
        uses: golang/govulncheck-action@v1
        with:
          go-package: ./...
          # Tells the action to look inside your backend directory
          work-dir: backend

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '24' # Change this to your required Node version
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install Frontend Dependencies
        working-directory: frontend
        run: npm install --legacy-peer-deps

      - name: Run npm audit
        working-directory: frontend
        run: npm audit