name: code-quality

on:
  push:
    branches: [main]

jobs:
  devsecops:
    
    # run code quality
    uses: ./.github/workflows/code-quality.yml

    # run secret scanning
    uses: ./.github/workflows/secret-scan.yml