name: code-quality

on:
  push:
    branches: [main]

jobs:
  # Job 1: Executes code quality checks
  code-check:
    uses: ./.github/workflows/code-quality.yml

  # Job 2: Executes secret scanning checks
  secret-check:
    uses: ./.github/workflows/secret-scan.yml

  # Job 3: Executes dependency scanning checks
  dependency-check:
    uses: ./.github/workflows/dependency-scan.yml

# Job 4: Executes dockerfile scanning checks
  dockerfile-check: 
    uses: ./.github/workflows/docker-scan.yml

  

  