name : Docker scan

on:
  workflow_call:

jobs:
  dockerscan:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        folders: [frontend, backend]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Lint Dockerfile for ${{matrix.folders}}
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ${{matrix.folders}}/Dockerfile

      - name: Scan Backend Dockerfile
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: 'fs'
          scan-ref: 'backend/'          # Targets only the backend folder
          scanners: 'config'            # Look exclusively for file configurations
          file-patterns: 'dockerfile:Dockerfile*' # Ignores k8s and scans ONLY Dockerfiles
          format: 'table'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'                # Fails the pipeline if Dockerfile issues exist

      - name: Scan Frontend Dockerfile
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: 'fs'
          scan-ref: 'frontend/'         # Targets only the frontend folder
          scanners: 'config'            # Look exclusively for file configurations
          file-patterns: 'dockerfile:Dockerfile*' # Ignores k8s and scans ONLY Dockerfiles
          format: 'table'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'           