name : Docker scan

on:
  workflow_call:

jobs:
  dockerscan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Scan All Dockerfiles
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: 'fs'          # Use filesystem mode so it navigates subfolders cleanly
          scan-ref: '.'            # Scan the whole repo root
          scanners: 'config'       # Explicitly isolate the scan to Dockerfiles/Configs
          format: 'table'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'           