name: matrix

on:
  workflow_dispatch: # Fixed typo here
  push:

jobs:
  matrix-frontend:
    runs-on: ubuntu-latest    

    defaults: # Moved out of strategy
      run:
        working-directory: frontend

    strategy:
      matrix:
        npmversion: ["20", "22", "24"] # Added space after colon
        
    steps: # Moved out of strategy
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.npmversion }}
          cache: 'npm'       
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm install --legacy-peer-deps
    
      - name: Run Lint
        run: npm run lint --if-present      

      - name: Run Tests
        run: npm test
